### ISSUE TITLE
NW.js 0.13 upgrade

### ISSUE THREAD

**Issue by le717** [BoatsAreRockable/Boats-Animator#108]
NW.js 0.13 will be coming out soon. It is currently on beta 5 and brings a slew of changes. We should upgrade, but there are some things we need to be aware of.

## NW.js ##
* There are now two builds of NW.js: Normal and SDK. We would the SDK build for development but Normal for releases.
* There are a number of [API changes](http://docs.nwjs.io/en/v0.13.0-beta5/For%20Users/Migration/From%200.12%20to%200.13/) ([more](http://nwjs.io/blog/v0.13.0-beta1/)) we need to update.
* Updating will hopefully also fix #87 for real.

## Chrome ##
* Chrome has been bumped to v49. This is a big jump, and we'll need to check for revised/renamed/moved JS APIs (particularly in the camera).
* v49 also brings a lot of ES6 support, including (but limited to `let`, `window.fetch`, and arrow functions). Once we can confirm we can successfully upgrade to v0.13, we can begin to make use of the latest JavaScript improvements!

## Web2Exe ##
* We can't upgrade without this.
* v0.4.3b provides initial 0.13 support, tracking jyapayne/Web2Executable#122

**Comment by le717** [comment]
I am actually looking into this right now. Um... let's just say we are going to have a _fun_ time. Perhaps the fact 0.13 is still a beta is making it harder, but initially, the app is DOA. I've had to make some changes just to make the index open, much less make the feed work, and I have yet to see how to get the main window to not totally crash. I'm posting my work [here](https://github.com/le717/animator/tree/nwjs-013), but that may be subject to change per an issue I am about to file).

**Comment by le717** [comment]
I've pushed my initial work to the [`nwjs-013`](https://github.com/BoatsAreRockable/animator/tree/nwjs-013) branch. This is going to be interesting...

**Comment by le717** [comment]
Update: Web2Exe does not yet support nw.js 0.13. See jyapayne/Web2Executable#121.

**Comment by BoatsAreRockable** [comment]
@le717 good news! I've tried BA in [nw.js v0.13.0-rc3](http://nwjs.io/blog/v0.13.0-rc3/) and unlike beta7 the animator actually loads with no errors.

Obvious there's still a lot to fix but not being DOA is a start...

Things that need fixing include:
* Launcher does not close when opening the animator
* "Return to main menu" does not work

**Comment by le717** [comment]
Well yea, I already fixed it from being dead on arrival (969d6685e0a1186ba094497feb2781414b3ec1b0). :P

**Comment by BoatsAreRockable** [comment]
@le717 Ah I didn't quite mean DOA... But the animator window didn't load so Dead On Animator? :P

**Comment by le717** [comment]
Either way, it's not totally dead, so that's a good thing. Hopefully I'll get my laptop back soon and resume work on this. https://twitter.com/_le717/status/708457145612824578

**Comment by le717** [comment]
A new, possibly compatible version of Web2Exe was just released. Although we have to get the app working first, it might be worth going ahead and testing it out and reporting any issues. Remember to use the non-SDK version! https://github.com/jyapayne/Web2Executable/releases/tag/v0.4.3b

**Comment by le717** [comment]
News!
* Web2Exe now officially supports nwjs 0.13
* nwjs 0.13 has been officially released!

I recommend we go ahead with updating to nwjs 0.13 before merging any more PRs. In this way, we can ensure all existing code works and we can make any changes needed. It also reduces the initial amount of code we need to test under 0.13. If we merged #122 then updated to 0.13, it
it would mean I would do double testing because I'd test it on both nwjs versions. Make sense?

Also, because this is a major update, I recommend marking this as part of the 0.7.x series. 0.6.x is done.

Finally, I will need to merge the latest changes with the `nwjs-013` branch before we can really do anything, but without my laptop I don't have a git client. If you want, you can go ahead and test the branch in the current state, but I myself want to update it (it will have a huge merge conflict, and conflicts can be very scary. I do not want you to handle one this size just yet. ;) ) and will need to before full testing begins.

**Comment by BoatsAreRockable** [comment]
@le717 This sounds good to me. I will update the roadmap.

**Comment by BoatsAreRockable** [comment]
@le717 I sort of went against your rather sensible advice... and merged master with nwjs-013 in a new [nwjs-013-merge-master](https://github.com/BoatsAreRockable/animator/tree/nwjs-013-merge-master) branch just to be safe. I believe I've done so successfully but I would welcome you eventually testing/reviewing it.

A couple of things to note with nwjs 0.13:
* Playback performance seems to be sluggish. It's definitely not running at 15FPS! Time to implement something [like this](https://github.com/BoatsAreRockable/animator/issues/112#issuecomment-193922618) I suppose.
* While most of the previous nwjs issues we were experiencing have been fixed; one that does remain is `window.reloadDev()` is not yet supported.
* Since 0.13 now has SDK builds with shortcuts to dev-tools, I'd like to remove the reload and dev tools buttons that are scattered around the around the interface. However there is no access to `window.reload()` or `window.reloadDev()` built in. Do you have any objections to this going?

**Comment by BoatsAreRockable** [comment]
Should this issue be closed now?

**Comment by le717** [comment]
That answer your question? :P
