### ISSUE TITLE
Stop node-modules from being packaged

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/Boats-Animator#134]
For some reason it hasn't occurred to me before that the node-modules directory is incorrectly packaged when Web2Exe is run. Either some method to exclude the folder from Web2Exe should be used or I should result to temporarily removing node-modules when packaging the app.

**Comment by le717** [comment]
Oh yup, that's how you blow up the release archives, for sure. :P

**Comment by BoatsAreRockable** [comment]
@le717 Any objections to solving this by moving node_modules to the root folder `animator` rather `animator/app`?
