### ISSUE TITLE
Playback does not occur at the right speed

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/Boats-Animator#158]
This is quite a major bug! And has been present since the update to nw.js 0.13. Using a metronome I've found the playback speed to be approximately 4 times slower than it should be. 

In #136 using `requestAnimationFrame` is suggested as a replacement for playback in the preview area. I can confirm removing the line `playback.setAttribute("src", capturedFrames[curPlayFrame]);` does greatly improve the performance of things..

I suppose the culprit is `setInterval` not performing as well as it should. Hopefully this can be optimised or an alternative method can be used.

**Comment by le717** [comment]
#136 will fix this. That was the plan the whole time once said playback in 0.13 was slower. Once the skip buttons are in place, I will be fixing the playback according to the rAF method I proposed.

**Comment by le717** [comment]
Currently working on #136/this issue on the `issue-136` branch.
