### ISSUE TITLE
Switch build method to nwjs-builder?

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/Boats-Animator#174]
This project operates quite similarly nw-builder, however it has more options and also appears to be more actively maintained. The project also works with node.js 6, something that nw-builder currently has issues with.

https://github.com/evshiron/nwjs-builder

Also on an unrelated note, I haven't worked on this project much recently because I've been busy with exams but hopefully by July I should be able to work on this more actively again :smile:

**Comment by le717** [comment]
Fixed in #176, closing.
