### ISSUE TITLE
First frame not stored if directory has to be created

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/boats-animator#186]
If the frame export location is set to a directory that no longer exists and a frame is captured, Boats Animator proceeds to recreate the directory and save captured frames to there. However when this occurs the first frame captured is not saved to this directory.

**Comment by le717** [comment]
Can you give a case when this happens and recreation steps? Do you delete the directory after app launch?

**Comment by le717** [comment]
Nevermind, I found the issue just by following the code. I've got this. In the meantime, if you want to go ahead and merge #187, you can.
