### ISSUE TITLE
Upgrade to nw.js stable channel

### ISSUE THREAD

**Issue by le717** [BoatsAreRockable/boats-animator#190]
We are currently running on the nw.js LTS channel (0.14.7). Before we push ahead with the WebRTC work, we really should upgrade to the nw.js stable channel (currently 0.19). The WebRTC spec is still being standardized, and there have been changes that would be beneficial to us that is available in newer Chrome versions. We should upgrade our current, limited use to the latest API to help us get a taste of how we need to engineer the rest.

This does raise the question of how often we update nw.js. We'll figure that out as we go, I guess, but I would suggest we do so at the beginning of every milestone and, depending on how long the milestone takes or features we can use come available (since this is not a super-actively maintained project), we can upgrade periodically.

**Comment by le717** [comment]
@BoatsAreRockable If you will, please add this to the WebRTC project. I don't have rights to do that, it seems.

**Comment by BoatsAreRockable** [comment]
Added this. It's strange how you can't update projects, I can't find any way of giving you the rights in settings. 

Upgrading to the latest stable nw.js version at the start of each milestone (as a general rule) sounds good.

I intend to release v0.7.4 once #122 is merged and then will move on to 0.8.x and nw.js 0.19.

**Comment by BoatsAreRockable** [comment]
Moved in 0.19.2 in the branch `nwjs-19`. As expected? There are WebRTC issues:
```
Uncaught TypeError: Illegal invocation
    at startup (main.js:179)
```

The contents of line 179 is:
```
    navigator.getMedia({ video: true },
```

I'll take a look at this tomorrow (unless someone gets there before me!).

**Comment by le717** [comment]
I've fixed the WebRTC API usage. There needs to be more testing, but so far all is working.

**Comment by le717** [comment]
Minor bug caught. Will fix right up.

![image](https://cloud.githubusercontent.com/assets/3382464/21443674/3605a486-c875-11e6-9e92-ac46866a0c6a.png)
