### ISSUE TITLE
Developer menu to toggle live reloading

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/boats-animator#199]
It would be helpful if Boats Animator's top menu had a "developer" sub-menu that only displayed when an SDK build of NW.js was run. The main option this would have would be a toggle to allow live reload of the application on changes. This would be very helpful and it would certainly help me speed up development.

For the reloading I would most likely use the snippet on the page below for [chokidar](https://github.com/paulmillr/chokidar):
https://github.com/nwjs/nw.js/wiki/Livereload-nw.js-on-changes
**Edit: turns out someone made a nice package for this. Will probably implement it.**
https://github.com/1j01/nw-dev

The easiest way I can think of to see if an SDK build is being run is to check if the `win.showDevTools()` command exists.

http://stackoverflow.com/questions/40453913/nwjs-is-there-way-to-check-if-useing-the-sdk-version
https://github.com/nwjs/nw.js/issues/5062

**Edit: the checking for win.showDevTools() method does not seem to work unfortunately**

**Comment by BoatsAreRockable** [comment]
Okay so I've decided I'm going to use nw-dev and add it to `package.json` as a `devDependency`.

I can't find a satisfactory way of implementing a check for an SDK build so as a quick fix I'm going to add `toggleLiveReload()` as a function of `utils.js` which you can simply run from the console. This function will add or remove `src="node_modules/nw-dev/lib/dev.js"` to a blank `script` tag with the id `#dev-reload-script` on each of the html pages.

**Comment by le717** [comment]
Implemented in #200.
