### ISSUE TITLE
Boats Animator is on Softpedia

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/boats-animator#202]
I was quite surprised to received an email today saying that Boats Animator is now on Softpedia:
http://www.softpedia.com/get/Multimedia/Video/Other-VIDEO-Tools/Boats-Animator.shtml

I'm really sure how to feel about this. I suppose it is nice to see the program get some exposure and I'm pretty sure that they are well within the rights of `GPL-3.0` to do so. I guess I'm not the biggest fan of them having ads though. But their email did specifically say:

> If you feel that having your product listed on Softpedia is not a benefit for you or simply need something changed or updated, please contact us via email at webmaster@softpedia.com and we will work with you to fix any problem you may have found with the product's listing.

From looking at [some discussions](https://softwareengineering.stackexchange.com/questions/114370/softpedia-published-some-of-my-open-source-projects-how-to-react), it does look like they actually do respect any wishes from a software's developer. Overall the page they made is pretty accurate so I guess I'll leave it up for now.

If anyone has any comments or suggestions regarding this please let me know below!

**Comment by le717** [comment]
> On the whole, this program looks very promising, and we were mostly impressed by its intuitive, novice-friendly design.

YES

> Once the missing features are implemented, this will be an excellent alternative to overly complex or expensive stop-motion animation tools.

YES

**Comment by le717** [comment]
FWIW, this is actually neat and gives motivation to continue work (as has already been shown!). However, I'm going to close the issue and if any issues arise from this, we can discuss/reopen if needed. :)
