### ISSUE TITLE
Support for multiple notifications

### ISSUE THREAD

**Issue by rioforce** [BoatsAreRockable/Boats-Animator#51]
If a notification is shown, and another comes up, it overwrites the current notification. There should either be a window for the notification list, or the notifications can stack on top of each other so when one goes away (maybe by clicking on it?), the other is shown.

**Comment by le717** [comment]
BTW, I am currently working on this.

**Comment by le717** [comment]
@BoatsAreRockable Milestone change proposal: push this to medium pri. for 0.7.x. #95 is already a decent change for 0.6.x. I'd like to get working on the camera code ASAP once the few remaining items for 0.6 are completed.

**Comment by BoatsAreRockable** [comment]
I will adjust the roadmap to account for this.

**Comment by BoatsAreRockable** [comment]
@le717 Moving to nwjs 0.13, keyframes, onion skinning changes, playback improvements and keyboard shortcuts seem large enough for 0.7.x. What would you think about this notification work, resolutions and camera selection being pushed to 0.8.x?

**Comment by le717** [comment]
I want to keep this on 0.7. I already have part of it set up in the current code. It will just be some refactoring and adjustments to implement this.
