### ISSUE TITLE
Recent news does not display when returning to the launcher

### ISSUE THREAD

**Issue by BoatsAreRockable** [BoatsAreRockable/Boats-Animator#87]
After returning to the launcher screen from the animator the recent news area does not display. The related error from the console is: `C:\Users\Charlie\Documents\GitHub\animator\app\js\feed.js:7 Uncaught TypeError: undefined is not a function`.

**Comment by BoatsAreRockable** [comment]
@le717 Would you be able to take a look at this sometime? Thanks

**Comment by le717** [comment]
That script was hard to make anyway.

**Comment by le717** [comment]
That script was hard to make anyway. Parsing XML (not to mention a huge one like that) is _insane_, slow, and really tricky. Your blog runs WordPress. Once [4.4 comes out](https://wordpress.org/news/) (due out [December](https://make.wordpress.org/core/version-4-4-project-schedule/)) perhaps you could update to it? I am pretty sure it will contain the new JSON feed built-in, one I have worked with before, is easier to use, and FWIW would make for a nicer feed script. If I am wrong about the JSON feed (which is possible) then I will look into fixing this. :)

**Comment by BoatsAreRockable** [comment]
Alright I'll look out for the update :)

What types of content will be displayed on the blog does need sorting out though. I do feel it is a good feature to have.

**Comment by le717** [comment]
> What types of content will be displayed on the blog does need sorting out though. I do feel it is a good feature to have.

Pardon? What you blog about is your own business. :P As long as you keep the Animator stuff in a specific category I can pull just that category and display that news. :P

**Comment by BoatsAreRockable** [comment]
Yes I mean I need to sort it out! The whole website generally needs sorting out too but that's a completely separate issue...

**Comment by le717** [comment]
WordPress 4.4 is out. I also found out the Jetpack extension has a blog JSON feed too, though I don't know if that's a different one or if the one in 4.4 replaces it.

**Comment by BoatsAreRockable** [comment]
I've just updated the site to WordPress 4.4.

**Comment by le717** [comment]
OK, I apologize. I checked out the API and as it turns out, there are _two_ JSON APIs. The one I was thinking of has been in [Jetpack](http://jetpack.me/support/json-api/) this whole time. The one that made it into WP core is different and will not work. I clearly did not do my homework. Sorry about that. :(

So, if you will enable the Jetpack JSON API, _then_ I can use the better API. I already tested it with a self-hosted WordPress I have control over and it is indeed the one I was thinking of the whole time.

Again, I'm sorry about this mixup.

**Comment by BoatsAreRockable** [comment]
No worries! I shall add the Jetpack plugin and then enable the JSON API. I've been meaning to add Jetpack for others reasons for a while now.

**Comment by BoatsAreRockable** [comment]
Having some issues with Jetpack. Would this plugin do the trick? https://wordpress.org/plugins/json-api/

**Comment by le717** [comment]
Yes, that plugin would also work, but I'm curious as to what kind of issues you are having with Jetpack.

**Comment by le717** [comment]
How did this go? Did you get Jetpack working or install the plugin?

**Comment by BoatsAreRockable** [comment]
The error I was getting was:
>  Your website needs to be publicly accessible to use Jetpack: site_inaccessible
> Error Details: The Jetpack server was unable to communicate with your site [HTTP 403]. Ask your web host if they allow connections from WordPress.com. If you need further assistance, contact Jetpack Support: http://jetpack.me/support/

This appears to be something I need to ask my web host to fix. Anyway, I have now installed the plugin.

**Comment by le717** [comment]
I am going to try to look into this and start working on a fix tonight. :)

**Comment by le717** [comment]
I actually got a good bit of this done, and by that I mean I am now successfully using the JSON feed. The error is sadly still present. I am sure it has something to do with NW.js. Hopefully 0.13 will fix it (I hope you are looking into upgrading to that). In the meantime I can work around the error,.

**Comment by BoatsAreRockable** [comment]
@le717 I've noticed that pressing the "refresh" button which runs `win.reloadDev();` causes the newsfeed to load properly without the error. While this probably doesn't explain the cause of the error it could allow us to create a fix for now.

**Comment by le717** [comment]
I'm not sure. We'd have to find a way to note "OK, we have/have not reloaded upon coming here" and react accordingly, else we would get stuck in an endless reload loop. The only way to do that would be externally, i.e, a file, but TBH I don't want to put up with that unless it is absolutely necessary.

**Comment by BoatsAreRockable** [comment]
@le717 I've been experimenting with this and it appears it may be similar to the issue there was with #126 involving contexts.

The line (currently 122) with the error `Uncaught TypeError: undefined is not a function` has `var request = new window.XMLHttpRequest();` and I think this could explain the issue (from the NW.js wiki):

> The Node.js global object is the global object in the Node's context. Any WebKit window's window object is not the global object and even is not implicitly available in the Node's context (the special case of node-main is the only exception), i.e. you have to (explicitly) pass the window object to your module's function if you need to access it.

https://github.com/nwjs/nw.js/wiki/Differences-of-JavaScript-contexts#features-andlimitations-of-thenodes-context

I don't fully understand this yet but the `node-main` exception could possibly suggest why the news feed loads the first time index.html is loaded.

Similarly to #126, this issue does not occur after removing the stuff related to module exports from index.js and newsfeed.js and simply using additional script tags on index.html.

**Comment by le717** [comment]
This is actually fixed by nwjs 0.13 with no changes needed (I tested it) but is still an issue in the current nw.js version. This should have been left open until it is is properly fixed.

**Comment by BoatsAreRockable** [comment]
Fixed in #145
